# Generated by Django 4.0.6 on 2022-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('is_publ', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
